### PR TITLE
Changed from C: drive only to all local hard drives.

### PR DESCRIPTION
**Pull request by gautelund**

### CODE REVIEW

**Comment by Robby-Swartenbroekx** [comment]
if you use pseverything, it does search on all local drives.

**Comment by gautelund** [comment]
Ah, OK, we don’t use that. Maybe our patch should have been built differently.

**Comment by Robby-Swartenbroekx** [comment]
but indeed, for the failover part, this can be usefull

**Comment by gautelund** [comment]
Yes, without Everything we really would want to search each disk. And we don't use that and definately wouldn't roll it out across servers "just" for this. If you want I can try to change the script, but I know neither PS1 (colleagues editet the script) nor git (managed to post the pull request with some effort).

**Comment by tdoan1** [comment]
This does code NOT return only local drives - it also returns mapped drives. Also with PowerShell 7, a "Temp" drive mount may be returned. 
`Get-PSDrive -PSProvider FileSystem | Where-Object {($_.Used -ne 0)} | select -expandProperty root`

I'm still researching solutions. WMI can help but the cmdlet may not be loaded by default in PowerShell 7. 
`Get-WmiObject -query "SELECT * from win32_logicaldisk where DriveType = '3'"`

**Comment by doodoooooo** [comment]
what about using "Get-CimInstance Win32_LogicalDisk | Where-Object {$_.Description -eq "Local Fixed Disk"} | Select-Object DeviceID"}"

**Comment by gautelund** [comment]
As others have done our modifications, I cannot say, I ask he who did.

**Comment by Robby-Swartenbroekx** [comment]
this is implemented in the latest version.

**Comment by gautelund** [comment]
Yeah, we didn't mind mapped drives as for us the script will always run in a context with no mappings. 
Note: Searching for NTFS drives will miss drives with ReFS. We actually use that.

**Comment by tdoan1** [comment]
In our environment, even though the context that will run this script will not itself map network drives, others on the system may do so at any time, such as while the script is processing. The mapped drive would have been scanned without this enhancement (use of [System.IO.DriveInfo]). 
However, I agree there is probably no justification for the restriction to include only NTFS volumes that's in place at the moment. I'd advocate for eliminating that and using this instead. 
`([System.IO.DriveInfo]::GetDrives() | Where-Object {$_.DriveType -eq 'Fixed'}).Name`

**Comment by prejay** [comment]
The reasons I chose the NTFS restriction in the end was for uniformity between Everything, Robocopy/GCI, as I can't guarantee that Everything has been setup to index non-NTFS filesystems and don't want to change any configurations with this script.

I did first experiment with $_.driveformat -ne $null in a non-public release as without this I did see some examples of drives being included that shouldn't be, and then went with the easy option of just restricting to NTFS.

Can you show the driveinfo output for your ReFS drive?

Prejay Shah
Systems Engineer

Telephone: +44 (0) 208 987 1150  
Support Desk: +44 (0) 208 987 1170 
Email: ***@***.***
Web: www.doherty.co.uk 
Address: 3 Water Lane, London, TW9 1TJ

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
